"""

`TclTk.Defs` module defines basic types and constants for the `TclTk` package.

"""
module Defs

# Assumed major and minor Tcl version.
const TCL_MAJOR_VERSION = 9
const TCL_MINOR_VERSION = 0

# Release numbers.
const TCL_ALPHA_RELEASE = Cint(0)
const TCL_BETA_RELEASE  = Cint(1)
const TCL_FINAL_RELEASE = Cint(2)

# Status constants.
const TCL_OK       = Cint(0)
const TCL_ERROR    = Cint(1)
const TCL_RETURN   = Cint(2)
const TCL_BREAK    = Cint(3)
const TCL_CONTINUE = Cint(4)

# Flags for evaluating scripts/commands.
const TCL_NO_EVAL       = Cint(0x010000)
const TCL_EVAL_GLOBAL   = Cint(0x020000)
const TCL_EVAL_DIRECT   = Cint(0x040000)
const TCL_EVAL_INVOKE   = Cint(0x080000)
const TCL_CANCEL_UNWIND = Cint(0x100000)
const TCL_EVAL_NOERR    = Cint(0x200000)

# Flags for Tcl variables.
const TCL_GLOBAL_ONLY    = Cint(1)
const TCL_NAMESPACE_ONLY = Cint(2)
const TCL_APPEND_VALUE   = Cint(4)
const TCL_LIST_ELEMENT   = Cint(8)
const TCL_LEAVE_ERR_MSG  = Cint(0x200)

# Opaque structures.
abstract type Tcl_Obj end
abstract type Tcl_Interp end
abstract type Tcl_Command_ end

# Procedures to be called by Tcl can be generated by `@cfunction` which returns a
# `Ptr{Cvoid}`.
const Tcl_CmdDeleteProc = Cvoid
const Tcl_CmdProc = Cvoid
const Tcl_FreeProc = Cvoid
const Tcl_IdleProc = Cvoid
const Tcl_ObjCmdProc = Cvoid

const Tcl_FreeInternalRepProc = Cvoid
const Tcl_DupInternalRepProc = Cvoid
const Tcl_UpdateStringProc = Cvoid
const Tcl_SetFromAnyProc = Cvoid

# Integer type for indices and sizes (since Tcl 9).
const Tcl_Size = TCL_MAJOR_VERSION ≥ 9 ? Cptrdiff_t : Cint

# Tcl wide integer is 64-bit integer.
const WideInt = Int64

# Client data used by commands and callbacks.
const ClientData = Ptr{Cvoid}

# Token used by Tcl to identify an object command.
const Tcl_Command = Ptr{Tcl_Command_}

# Flags for settings the result.
const TCL_VOLATILE = Ptr{Tcl_FreeProc}(1)
const TCL_STATIC   = Ptr{Tcl_FreeProc}(0)
const TCL_DYNAMIC  = Ptr{Tcl_FreeProc}(3)

# Flags for Tcl processing events. Set TCL_DONT_WAIT to not sleep: process only events that
# are ready at the time of the call. Set TCL_ALL_EVENTS to process all kinds of events:
# equivalent to OR-ing together all of the below flags or specifying none of them.
const TCL_DONT_WAIT     = Cint(1<<1)
const TCL_WINDOW_EVENTS = Cint(1<<2) # Process window system events.
const TCL_FILE_EVENTS   = Cint(1<<3) # Process file events.
const TCL_TIMER_EVENTS  = Cint(1<<4) # Process timer events.
const TCL_IDLE_EVENTS   = Cint(1<<5) # Process idle callbacks.
const TCL_ALL_EVENTS    = ~TCL_DONT_WAIT      # Process all kinds of events.

"""
    TclTk.Defs.Tcl_ObjType

Julia equivalent type of C structure `Tcl_ObjType` defined in `<tcl.h>`.

"""
struct Tcl_ObjType
    name::Cstring
    freeIntRepProc::Ptr{Tcl_FreeInternalRepProc}
    dupIntRepProc::Ptr{Tcl_DupInternalRepProc}
    updateStringProc::Ptr{Tcl_UpdateStringProc}
    setFromAnyProc::Ptr{Tcl_SetFromAnyProc}
    # NOTE there are more fields below since Tcl 9. But we do not access them directly.
end

end # module
